version: '3.8'
services:
  app:
    build: .
    ports:
      - '4567:3000'
    volumes:
      - ./uploads:/app/uploads
      - ./dev.db:/app/dev.db
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DISCOGS_TOKEN: ${DISCOGS_TOKEN}
      DATABASE_URL: file:./dev.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/records || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5